# Generated by Django 5.2.10 on 2026-02-02 17:42

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contract",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                (
                    "budget_hours_total",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("draft", "Draft"), ("active", "Active"), ("closed", "Closed")],
                        default="draft",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Staff",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("email", models.EmailField(max_length=254, unique=True)),
                ("first_name", models.CharField(max_length=150)),
                ("last_name", models.CharField(max_length=150)),
                (
                    "status",
                    models.CharField(
                        choices=[("active", "Active"), ("inactive", "Inactive")], default="active", max_length=20
                    ),
                ),
                (
                    "role",
                    models.CharField(
                        choices=[("member", "Member"), ("manager", "Manager"), ("admin", "Admin")],
                        default="member",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={
                "ordering": ["last_name", "first_name"],
            },
        ),
        migrations.CreateModel(
            name="Deliverable",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("start_date", models.DateField(blank=True, null=True)),
                ("due_date", models.DateField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("planned", "Planned"),
                            ("in_progress", "In progress"),
                            ("complete", "Complete"),
                            ("blocked", "Blocked"),
                        ],
                        default="planned",
                        max_length=20,
                    ),
                ),
                ("name", models.CharField(default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "contract",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="deliverables", to="core.contract"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverableTimeEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField()),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("external_source", models.CharField(blank=True, default="", max_length=100)),
                ("external_id", models.CharField(blank=True, default="", max_length=200)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="time_entries", to="core.deliverable"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT, related_name="time_entries", to="core.staff"
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverableStatusUpdate",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_end", models.DateField()),
                (
                    "status",
                    models.CharField(
                        choices=[("on_track", "On track"), ("at_risk", "At risk"), ("off_track", "Off track")],
                        max_length=20,
                    ),
                ),
                ("summary", models.TextField(blank=True, default="")),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="status_updates",
                        to="core.deliverable",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="status_updates",
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="DeliverableAssignment",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "expected_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                ("is_lead", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="assignments", to="core.deliverable"
                    ),
                ),
                (
                    "staff",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="deliverable_assignments",
                        to="core.staff",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Task",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                (
                    "planned_hours",
                    models.DecimalField(
                        decimal_places=2,
                        default=Decimal("0"),
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0"))],
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("todo", "To do"),
                            ("in_progress", "In progress"),
                            ("done", "Done"),
                            ("blocked", "Blocked"),
                        ],
                        default="todo",
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "assignee",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="tasks",
                        to="core.staff",
                    ),
                ),
                (
                    "deliverable",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, related_name="tasks", to="core.deliverable"
                    ),
                ),
            ],
        ),
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(fields=["contract"], name="core_delive_contrac_4ecf37_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverabletimeentry",
            index=models.Index(fields=["deliverable", "entry_date"], name="core_delive_deliver_6a53a4_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverabletimeentry",
            index=models.Index(fields=["staff", "entry_date"], name="core_delive_staff_i_0b8b5b_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverablestatusupdate",
            index=models.Index(fields=["deliverable", "period_end"], name="core_delive_deliver_72e11f_idx"),
        ),
        migrations.AddConstraint(
            model_name="deliverablestatusupdate",
            constraint=models.UniqueConstraint(
                fields=("deliverable", "period_end"), name="uniq_deliverable_period_end"
            ),
        ),
        migrations.AddIndex(
            model_name="deliverableassignment",
            index=models.Index(fields=["deliverable"], name="core_delive_deliver_d1cba2_idx"),
        ),
        migrations.AddIndex(
            model_name="deliverableassignment",
            index=models.Index(fields=["staff"], name="core_delive_staff_i_d9b942_idx"),
        ),
        migrations.AddConstraint(
            model_name="deliverableassignment",
            constraint=models.UniqueConstraint(
                fields=("deliverable", "staff"), name="uniq_deliverable_staff_assignment"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["deliverable"], name="core_task_deliver_a8fffc_idx"),
        ),
    ]
