# Generated by Django 5.2.10 on 2026-02-05 18:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_staff_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverablestatusupdate",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name="deliverabletimeentry",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="deliverabletimeentry",
            name="external_id",
            field=models.CharField(
                blank=True,
                default="",
                help_text="External system's unique identifier for this time entry",
                max_length=200,
            ),
        ),
        migrations.AlterField(
            model_name="deliverabletimeentry",
            name="external_source",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Source system identifier (e.g., 'jira', 'harvest', 'toggl')",
                max_length=100,
            ),
        ),
        migrations.AddIndex(
            model_name="deliverabletimeentry",
            index=models.Index(fields=["external_source", "external_id"], name="core_delive_externa_a235e3_idx"),
        ),
        migrations.AddConstraint(
            model_name="contract",
            constraint=models.CheckConstraint(
                condition=models.Q(("end_date__gte", models.F("start_date"))), name="contract_end_after_start"
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverable",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    ("due_date__gte", models.F("start_date")),
                    ("due_date__isnull", True),
                    ("start_date__isnull", True),
                    _connector="OR",
                ),
                name="deliverable_due_after_start",
            ),
        ),
        migrations.AddConstraint(
            model_name="deliverabletimeentry",
            constraint=models.UniqueConstraint(
                condition=models.Q(("external_source__gt", "")),
                fields=("external_source", "external_id"),
                name="unique_external_time_entry",
            ),
        ),
    ]
