name: Feature request
description: Suggest an idea for TaskRoot
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for the suggestion! Please include enough context to evaluate it.

  - type: textarea
    id: problem
    attributes:
      label: Problem / use-case
      description: What problem does this solve? Who is it for?
      placeholder: Describe the need.
    validations:
      required: true

  - type: textarea
    id: proposal
    attributes:
      label: Proposed solution
      description: What would you like to happen?
      placeholder: Describe the feature.
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives considered
      placeholder: Any other approaches you’ve considered?
    validations:
      required: false
