# Generated by Django 5.2.10 on 2026-02-05 22:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0003_deliverablestatusupdate_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="client_name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="contract",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
    ]
