# Generated by Django 5.2.10 on 2026-02-05 22:53

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_contract_client_name_contract_name"),
    ]

    operations = [
        migrations.RenameField(
            model_name="contract",
            old_name="budget_hours_total",
            new_name="budget_hours",
        ),
        migrations.RenameField(
            model_name="deliverableassignment",
            old_name="expected_hours",
            new_name="budget_hours",
        ),
        migrations.RenameField(
            model_name="task",
            old_name="planned_hours",
            new_name="budget_hours",
        ),
        migrations.AddField(
            model_name="deliverable",
            name="budget_hours",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=10,
                validators=[django.core.validators.MinValueValidator(Decimal("0"))],
            ),
        ),
    ]
