# Generated by Django 5.2.10 on 2026-02-06 03:20

from decimal import Decimal

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0005_rename_budget_hours_total_contract_budget_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="expected_hours_per_week",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("40.00"),
                help_text="Expected number of hours this staff member works per week",
                max_digits=5,
            ),
        ),
    ]
