# Generated by Django 5.2.10 on 2026-02-06 04:03

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0006_staff_expected_hours_per_week"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="deliverabletimeentry",
            name="core_delive_staff_i_0b8b5b_idx",
        ),
        migrations.RemoveField(
            model_name="deliverabletimeentry",
            name="staff",
        ),
    ]
