# Generated by Django 5.2.10 on 2026-02-06 04:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0007_remove_deliverabletimeentry_core_delive_staff_i_0b8b5b_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="deliverable",
            name="charge_code",
            field=models.CharField(blank=True, default="", max_length=100),
        ),
    ]
