# Generated by Django 5.2.10 on 2026-02-06 05:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0008_deliverable_charge_code"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="deliverable",
            name="deliverable_due_after_start",
        ),
        migrations.RemoveField(
            model_name="deliverable",
            name="start_date",
        ),
        migrations.RemoveField(
            model_name="deliverable",
            name="due_date",
        ),
        migrations.AddField(
            model_name="deliverable",
            name="target_completion_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
