# Generated by Django 5.2.10 on 2026-02-12 17:11

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0010_contract_contract_type"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="deliverable",
            index=models.Index(fields=["charge_code"], name="core_delive_charge__b01704_idx"),
        ),
    ]
