# Generated by Django 5.2.10 on 2026-02-13 19:31

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0011_alter_deliverable_charge_code_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="percent_complete",
            field=models.DecimalField(
                decimal_places=2,
                default=Decimal("0"),
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
