# Generated by Django 5.2.10 on 2026-03-03 21:30

from decimal import Decimal

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0017_contract_amount_and_invoice_updates"),
    ]

    def backfill_charge_codes(apps, schema_editor):
        Deliverable = apps.get_model("core", "Deliverable")
        ChargeCode = apps.get_model("core", "ChargeCode")

        deliverables = Deliverable.objects.exclude(charge_code="").order_by("id")
        for deliverable in deliverables:
            code = (deliverable.charge_code or "").strip()
            if not code:
                continue

            charge_code, _ = ChargeCode.objects.get_or_create(
                code=code,
                defaults={
                    "description": "",
                    "is_active": True,
                },
            )

            if charge_code.deliverable_id is None:
                charge_code.deliverable_id = deliverable.id
                charge_code.save(update_fields=["deliverable", "updated_at"])

    operations = [
        migrations.CreateModel(
            name="ChargeCode",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("code", models.CharField(max_length=100, unique=True)),
                ("description", models.CharField(blank=True, default="", max_length=255)),
                (
                    "allotted_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=10,
                        null=True,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="UnmappedChargeCodeEntry",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("entry_date", models.DateField()),
                (
                    "hours",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[django.core.validators.MinValueValidator(Decimal("0.01"))],
                    ),
                ),
                ("note", models.TextField(blank=True, default="")),
                ("source_file", models.CharField(blank=True, default="", max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name="chargecode",
            name="deliverable",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="charge_code_mapping",
                to="core.deliverable",
            ),
        ),
        migrations.AddField(
            model_name="unmappedchargecodeentry",
            name="charge_code",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, related_name="unmapped_entries", to="core.chargecode"
            ),
        ),
        migrations.RunPython(backfill_charge_codes, migrations.RunPython.noop),
        migrations.AddIndex(
            model_name="chargecode",
            index=models.Index(fields=["code"], name="core_charge_code_8a2110_idx"),
        ),
        migrations.AddIndex(
            model_name="chargecode",
            index=models.Index(fields=["is_active"], name="core_charge_is_acti_dc1a61_idx"),
        ),
        migrations.AddIndex(
            model_name="unmappedchargecodeentry",
            index=models.Index(fields=["charge_code", "entry_date"], name="core_unmapp_charge__c2d68f_idx"),
        ),
        migrations.AddIndex(
            model_name="unmappedchargecodeentry",
            index=models.Index(fields=["entry_date"], name="core_unmapp_entry_d_e6ef5c_idx"),
        ),
    ]
