# Generated by Django 5.2.10 on 2026-03-03 21:34

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0018_chargecode_unmappedchargecodeentry_and_more"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="contractinvoiceupdate",
            new_name="core_contra_contrac_07aeec_idx",
            old_name="core_contra_contrac_4505a4_idx",
        ),
        migrations.AlterField(
            model_name="initiativeweeklyupdate",
            name="percent_complete",
            field=models.DecimalField(
                decimal_places=2,
                max_digits=5,
                validators=[
                    django.core.validators.MinValueValidator(Decimal("0")),
                    django.core.validators.MaxValueValidator(Decimal("100")),
                ],
            ),
        ),
    ]
