# Generated by Django 5.2.10 on 2026-03-03

from decimal import Decimal

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0019_rename_core_contra_contrac_4505a4_idx_core_contra_contrac_07aeec_idx_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargecode",
            name="allotted_hours",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=10,
                null=True,
                validators=[django.core.validators.MinValueValidator(Decimal("0.00"))],
            ),
        ),
    ]
