# Generated by Django 5.2.10 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0020_chargecode_allotted_hours"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargecode",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="chargecode",
            index=models.Index(fields=["start_date"], name="core_charge_start_d_4c8bd5_idx"),
        ),
    ]
