# Generated by Django 5.2.10 on 2026-03-03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0021_chargecode_start_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="chargecode",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddIndex(
            model_name="chargecode",
            index=models.Index(fields=["end_date"], name="core_charge_end_dat_5a7fb4_idx"),
        ),
    ]
