# Generated by Django 5.2.10 on 2026-03-03 22:35

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0022_chargecode_end_date"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="chargecode",
            new_name="core_charge_start_d_ccbb8f_idx",
            old_name="core_charge_start_d_4c8bd5_idx",
        ),
        migrations.RenameIndex(
            model_name="chargecode",
            new_name="core_charge_end_dat_38782c_idx",
            old_name="core_charge_end_dat_5a7fb4_idx",
        ),
    ]
